### ISSUE TITLE
Root role not found in upstream key store

### ISSUE THREAD

**Issue by bclouser** [advancedtelematic/director#147]
Not an issue, just a question.

I am seeing this error in aktualizr when it requests 1.root.json file from the director upon initial connection to OTA community edition.

`response: {"code":"root_role_not_found","description":"root role was not found in upstream key store","cause":null,"errorId":"7940310c-9d04-49aa-8447-9c924d365513"}`

This is a custom in-house deployment of OTA ce but we haven't deviated too far yet.

I am looking for some reasons why this error might occur? My root key is missing somewhere it seems? I just went through and verified my keys and certs are fresh. I haven't yet rotated the initial root key, but I wouldn't think that would matter as the initial key might be insecure, but should still work.

Any help is appreciated.
-Ben

**Comment by jerrytrieu** [comment]
This `root_role_not_found` error usually indicates that keys have not yet been generated for either the director or the TUF repository. It may take some time on first login (loading of the web app) to generate all keys.

If aktualizr gets 404 on requesting `1.root.json`, then this is fixed by https://github.com/advancedtelematic/ota-tuf/pull/205.
A workaround for this is logging in a second time (loading of the web app in private window w/o cache).

**Comment by doanac** [comment]
I'm seeing this, but the http-code is actually 424:
~~~
response http code: 424
response: {"code":"root_role_not_found","description":"root role was not found in upstream key store","cause":null,"errorId":"1982cdc5-b209-4733-a12f-4836f0565ce5"}
~~~

**Comment by bclouser** [comment]
i was seeing 424 as well

**Comment by doanac** [comment]
Okay - i have found a fix for me. And since @bclouser uses my same deployment, this may help. I've updated my containers from ota-community-edition with these versions:

~~~
director_daemon_docker_image: advancedtelematic/director:0.5.3-3-gbe04a4a
director_docker_image: advancedtelematic/director:0.5.3-3-gbe04a4a

tuf_keyserver_daemon_docker_image: advancedtelematic/tuf-keyserver:0.5.0-8-g8802e1c
tuf_keyserver_docker_image: advancedtelematic/tuf-keyserver:0.5.0-8-g8802e1c
tuf_reposerver_docker_image: advancedtelematic/tuf-reposerver:0.5.0-8-g8802e1c

treehub_docker_image: advancedtelematic/treehub:0.1.27-2-g5f9fe2a
~~~

I need to update the device-registry, but I'll do that separate from this.

**Comment by vishalbhoj** [comment]
I am seeing 424 as well. Please update the images.yaml with working versions to use.

**Comment by bclouser** [comment]
So i still think a working set of images would be nice. But this issue is super old. I am closing it.
